server:
  port: 8761    # Standard Eureka port

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false    # VERY IMPORTANT
    fetch-registry: false          # VERY IMPORTANT

  server:
    enable-self-preservation: false
