server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: mypass123
  liquibase:
    enabled: true
    change-log: classpath:db-changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
